services:
  mysql:
    image: mysql:8.0
    container_name: circuit-bazaar-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: circuit_bazaar
      MYSQL_USER: circuit
      MYSQL_PASSWORD: circuit
    volumes:
      - second-year-poo_mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - circuit-bazaar
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: circuit-bazaar-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: circuit
      PMA_PASSWORD: circuit
      UPLOAD_LIMIT: 64M
    networks:
      - circuit-bazaar
    restart: always
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  second-year-poo_mysql_data:

networks:
  circuit-bazaar:
    driver: bridge
